/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */



package org.apache.parquet.crypto.keytools;

import java.io.IOException;

public interface KmsClient {
  
  public boolean supportsServerSideWrapping();
  
  /**
   * stored in KMS, or autogenerated in KMS
   * 
   * @param keyID
   * @return
   * @throws UnsupportedOperationException
   * @throws IOException
   */
  public String getKey(String keyID)  throws UnsupportedOperationException, IOException;
  
  /**
   * result includes everything provided by KMS (inc current version of master key, etc)
   * 
   * @param dataKey Base64 encoded data encryption key
   * @param masterKeyID String ID of the master key
   * @return
   * @throws IOException 
   */
  public String wrapKey(String dataKey, String masterKeyID) throws UnsupportedOperationException, IOException;
  
  /**
   * 
   * @param wrappedKey includes everything provided by KMS upon wrapping (inc version of master key, etc)
   * @param masterKeyID
   * @return Base64 encoded data encryption key
   */
  public String unwrapKey(String wrappedKey, String masterKeyID) throws UnsupportedOperationException, IOException;
}
